// ---------------------------------------------------------------------------
// Balancing Act – Complete Metric Catalog (PRD Section 11)
// Used by the seeding API route to populate Supabase tables for new users.
// ---------------------------------------------------------------------------

// ── Enum types ──────────────────────────────────────────────────────────────

export type MeasurementType =
  | 'binary'
  | 'scale'
  | 'count'
  | 'percentage'
  | 'currency'
  | 'target';

export type MeasurementFrequency =
  | 'daily'
  | 'weekly'
  | 'monthly'
  | 'quarterly'
  | 'biannual'
  | 'annual'
  | 'one_time';

export type Polarity = 'positive' | 'negative';

export type MetricTier = 'monthly' | 'yearly' | 'life';

export type DisplayFormat =
  | 'percentage'
  | 'number'
  | 'boolean'
  | 'hours'
  | 'currency';

// ── Interfaces ──────────────────────────────────────────────────────────────

export interface SeedCategory {
  name: string;
  description: string;
  weight: number;
  display_order: number;
  color: string;
  icon: string;
}

export interface SeedMetric {
  category_name: string;
  name: string;
  measurement_type: MeasurementType;
  measurement_frequency: MeasurementFrequency;
  weight: number;
  polarity: Polarity;
  tier: MetricTier;
  display_order: number;
  display_format: DisplayFormat;
  ai_extraction_hints: string[];
  scale_min?: number;
  scale_max?: number;
}

export interface SeedLifeGoal {
  category_name: string;
  name: string;
  weight: number;
}

// ── Categories ──────────────────────────────────────────────────────────────

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: 'Spiritual',
    description: 'Spiritual growth, scripture study, prayer, and living gospel principles.',
    weight: 0.125,
    display_order: 1,
    color: '#C49A6C',
    icon: 'star',
  },
  {
    name: 'Family',
    description: 'Family relationships, quality time, and strengthening bonds with loved ones.',
    weight: 0.125,
    display_order: 2,
    color: '#C47060',
    icon: 'heart',
  },
  {
    name: 'Personal',
    description: 'Personal habits, organization, hygiene, and self-discipline.',
    weight: 0.125,
    display_order: 3,
    color: '#7BAF7E',
    icon: 'user',
  },
  {
    name: 'Emotional',
    description: 'Emotional well-being, stress management, and cultivating positive feelings.',
    weight: 0.125,
    display_order: 4,
    color: '#D4A96A',
    icon: 'smile',
  },
  {
    name: 'Physical',
    description: 'Physical health, exercise, nutrition, and body composition goals.',
    weight: 0.125,
    display_order: 5,
    color: '#5A9BB5',
    icon: 'activity',
  },
  {
    name: 'Financial',
    description: 'Financial security, investments, budgeting, and wealth building.',
    weight: 0.125,
    display_order: 6,
    color: '#6BAA8C',
    icon: 'dollar-sign',
  },
  {
    name: 'Intellectual',
    description: 'Learning, language study, reading, and expanding knowledge.',
    weight: 0.125,
    display_order: 7,
    color: '#9688B5',
    icon: 'book-open',
  },
];

// ── Helper: scale ranges by measurement type ────────────────────────────────
// binary  → 0–1
// scale   → 0–5
// count   → 0–10
// percentage → 0–100
// currency → (none)
// target  → (none)

// ── Metrics ─────────────────────────────────────────────────────────────────

export const SEED_METRICS: SeedMetric[] = [
  // =========================================================================
  // 11.1 SPIRITUAL
  // =========================================================================

  // ── Spiritual · Monthly ──────────────────────────────────────────────────
  {
    category_name: 'Spiritual',
    name: 'Keeping the Commandments',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.40,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'boolean',
    ai_extraction_hints: ['commandments', 'obedient', 'obedience'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Tithing',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.15,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'boolean',
    ai_extraction_hints: ['tithing', 'tithe', 'paid tithing'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Church Attendance',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.19,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'boolean',
    ai_extraction_hints: ['church', 'sacrament meeting', 'attended church'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Ponderize One Scripture',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'boolean',
    ai_extraction_hints: ['ponderize', 'memorize scripture', 'scripture memory'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Temple Attendance',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'boolean',
    ai_extraction_hints: ['temple', 'went to temple'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Monthly Fasts',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.04,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'boolean',
    ai_extraction_hints: ['fast', 'fasting', 'fast sunday'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Home Teaching / Ministering',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.01,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 7,
    display_format: 'boolean',
    ai_extraction_hints: ['ministering', 'home teaching', 'visited families'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Family History Work Hours',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.01,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 8,
    display_format: 'number',
    ai_extraction_hints: ['family history', 'genealogy', 'familysearch', 'indexing'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Spiritual',
    name: 'Daily Strive to Live Like Christ',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 9,
    display_format: 'number',
    ai_extraction_hints: ['christlike', 'live like christ', 'WWJD'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Spiritual',
    name: 'Daily Sincere Scripture Reading',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 10,
    display_format: 'boolean',
    ai_extraction_hints: ['scripture reading', 'read scriptures', 'BOM', 'bible'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Minor Transgressions',
    measurement_type: 'count',
    measurement_frequency: 'daily',
    weight: 0.03,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 11,
    display_format: 'number',
    ai_extraction_hints: ['transgression', 'sin', 'mistake', 'slipped up'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Spiritual',
    name: 'Serious Commandment Violations',
    measurement_type: 'count',
    measurement_frequency: 'daily',
    weight: 0.25,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 12,
    display_format: 'number',
    ai_extraction_hints: ['serious sin', 'major transgression', 'violation'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Spiritual',
    name: 'Feelings of Forgiveness',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.17,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 13,
    display_format: 'number',
    ai_extraction_hints: ['forgiveness', 'forgiven', 'feel forgiven'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Spiritual',
    name: 'Repentance',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.02,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 14,
    display_format: 'boolean',
    ai_extraction_hints: ['repent', 'repentance', 'repented'],
    scale_min: 0,
    scale_max: 1,
  },

  // ── Spiritual · Yearly ───────────────────────────────────────────────────
  {
    category_name: 'Spiritual',
    name: 'Book of Mormon Reading',
    measurement_type: 'percentage',
    measurement_frequency: 'annual',
    weight: 0.20,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 15,
    display_format: 'percentage',
    ai_extraction_hints: ['book of mormon', 'BOM reading progress'],
    scale_min: 0,
    scale_max: 100,
  },
  {
    category_name: 'Spiritual',
    name: 'New Testament Reading',
    measurement_type: 'percentage',
    measurement_frequency: 'annual',
    weight: 0.10,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 16,
    display_format: 'percentage',
    ai_extraction_hints: ['new testament reading'],
    scale_min: 0,
    scale_max: 100,
  },
  {
    category_name: 'Spiritual',
    name: 'Old Testament Reading',
    measurement_type: 'percentage',
    measurement_frequency: 'annual',
    weight: 0.02,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 17,
    display_format: 'percentage',
    ai_extraction_hints: ['old testament reading'],
    scale_min: 0,
    scale_max: 100,
  },
  {
    category_name: 'Spiritual',
    name: 'Pearl of Great Price Reading',
    measurement_type: 'percentage',
    measurement_frequency: 'annual',
    weight: 0.05,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 18,
    display_format: 'percentage',
    ai_extraction_hints: ['pearl of great price'],
    scale_min: 0,
    scale_max: 100,
  },
  {
    category_name: 'Spiritual',
    name: 'Doctrine and Covenants Reading',
    measurement_type: 'percentage',
    measurement_frequency: 'annual',
    weight: 0.10,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 19,
    display_format: 'percentage',
    ai_extraction_hints: ['D&C', 'doctrine and covenants'],
    scale_min: 0,
    scale_max: 100,
  },
  {
    category_name: 'Spiritual',
    name: 'General Conference (in English)',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.25,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 20,
    display_format: 'boolean',
    ai_extraction_hints: ['general conference', 'conference'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Monthly Temple Trip',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.13,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 21,
    display_format: 'boolean',
    ai_extraction_hints: ['temple trip', 'monthly temple'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Spiritual',
    name: 'Quarterly Christlike Attributes',
    measurement_type: 'scale',
    measurement_frequency: 'quarterly',
    weight: 0.15,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 22,
    display_format: 'number',
    ai_extraction_hints: ['christlike attributes', 'self assessment'],
    scale_min: 0,
    scale_max: 5,
  },

  // =========================================================================
  // 11.2 FAMILY
  // =========================================================================

  // ── Family · Monthly ─────────────────────────────────────────────────────
  {
    category_name: 'Family',
    name: '2 Hours a Day Min with Family',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.14,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'boolean',
    ai_extraction_hints: ['family time', 'time with family', 'tasha', 'hazel'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Weekly Dates with Wife',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.15,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'boolean',
    ai_extraction_hints: ['date night', 'date with wife', 'tasha date'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Weekly Email for Parents',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.60,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'boolean',
    ai_extraction_hints: ['email parents', 'wrote parents'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Walk the Dog 5 Times a Week',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.11,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'number',
    ai_extraction_hints: ['walk dog', 'walked the dog'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Family',
    name: 'Phone Call Parents Every Month',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'boolean',
    ai_extraction_hints: ['called parents', 'phone call parents'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Family Night',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'boolean',
    ai_extraction_hints: ['family night', 'FHE', 'family home evening'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Personal Time with Every Child',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 7,
    display_format: 'boolean',
    ai_extraction_hints: ['time with kids', 'individual time'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Family Meals',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 8,
    display_format: 'boolean',
    ai_extraction_hints: ['family dinner', 'ate together'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Family Scriptures',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 9,
    display_format: 'boolean',
    ai_extraction_hints: ['family scriptures', 'read together'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Family Prayers',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 10,
    display_format: 'boolean',
    ai_extraction_hints: ['family prayer', 'prayed together'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Family Reading Time',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 11,
    display_format: 'boolean',
    ai_extraction_hints: ['family reading', 'read to kids'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Weekly Family Interviews',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 12,
    display_format: 'boolean',
    ai_extraction_hints: ['family interview', 'companionship inventory'],
    scale_min: 0,
    scale_max: 1,
  },

  // ── Family · Yearly ──────────────────────────────────────────────────────
  {
    category_name: 'Family',
    name: 'Memorize Full Names of All Siblings',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.17,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 13,
    display_format: 'boolean',
    ai_extraction_hints: ['siblings names'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Memorize Siblings Birthdays',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.17,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 14,
    display_format: 'boolean',
    ai_extraction_hints: ['siblings birthdays'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Memorize Siblings Anniversaries',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.17,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 15,
    display_format: 'boolean',
    ai_extraction_hints: ['siblings anniversaries'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Memorize Nieces and Nephews Full Names',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.17,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 16,
    display_format: 'boolean',
    ai_extraction_hints: ['nieces nephews names'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Memorize Nieces and Nephews Birthdays',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.17,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 17,
    display_format: 'boolean',
    ai_extraction_hints: ['nieces nephews birthdays'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Family',
    name: 'Memorize Nieces and Nephews Anniversaries',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.15,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 18,
    display_format: 'boolean',
    ai_extraction_hints: ['nieces nephews anniversaries'],
    scale_min: 0,
    scale_max: 1,
  },

  // =========================================================================
  // 11.3 PERSONAL
  // =========================================================================

  // ── Personal · Monthly ───────────────────────────────────────────────────
  {
    category_name: 'Personal',
    name: 'Daily Journal',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'boolean',
    ai_extraction_hints: ['journal', 'journaled', 'wrote in journal'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Daily Goal App',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'boolean',
    ai_extraction_hints: ['goal app', 'goals', 'daily goals'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Daily Life Measurements',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'boolean',
    ai_extraction_hints: ['measurements', 'tracked', 'life measurements'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Clean Room',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.09,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'boolean',
    ai_extraction_hints: ['clean room', 'room clean'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Make Your Bed',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.09,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'boolean',
    ai_extraction_hints: ['made bed', 'make bed'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Keep Desk Clear',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'boolean',
    ai_extraction_hints: ['desk clear', 'clean desk'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Clean Home',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 7,
    display_format: 'boolean',
    ai_extraction_hints: ['clean house', 'cleaned home'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Go to Bed Before 12:00',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 8,
    display_format: 'boolean',
    ai_extraction_hints: ['bed on time', 'sleep early', 'bed before midnight'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Get Up Before 6:00',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 9,
    display_format: 'boolean',
    ai_extraction_hints: ['wake up early', 'up before 6', 'early morning'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Brush Teeth',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.03,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 10,
    display_format: 'boolean',
    ai_extraction_hints: ['brush teeth', 'brushed teeth'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Practice Good Hygiene',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.03,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 11,
    display_format: 'boolean',
    ai_extraction_hints: ['hygiene', 'shower', 'grooming'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Laundry',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.03,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 12,
    display_format: 'boolean',
    ai_extraction_hints: ['laundry', 'washed clothes'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Grocery Shopping',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.01,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 13,
    display_format: 'boolean',
    ai_extraction_hints: ['grocery', 'groceries', 'shopping'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Personal Interviews Once a Week',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 14,
    display_format: 'boolean',
    ai_extraction_hints: ['personal interview'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Do Hard Things',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.04,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 15,
    display_format: 'boolean',
    ai_extraction_hints: ['hard things', 'challenged myself'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Strictly Avoid Addictions',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 16,
    display_format: 'boolean',
    ai_extraction_hints: ['addiction', 'avoid addiction', 'clean'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Personal',
    name: 'Motivational Minute',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 17,
    display_format: 'boolean',
    ai_extraction_hints: ['motivational', 'motivation', 'inspired'],
    scale_min: 0,
    scale_max: 1,
  },

  // Personal has no yearly metrics.

  // =========================================================================
  // 11.4 EMOTIONAL
  // =========================================================================

  // ── Emotional · Monthly ──────────────────────────────────────────────────
  {
    category_name: 'Emotional',
    name: 'Positive',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'number',
    ai_extraction_hints: ['positive', 'felt positive'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Patience',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'number',
    ai_extraction_hints: ['patient', 'patience'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Joy',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'number',
    ai_extraction_hints: ['joy', 'joyful', 'happy'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Peace',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.07,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'number',
    ai_extraction_hints: ['peace', 'peaceful', 'calm'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Fun',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.01,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'number',
    ai_extraction_hints: ['fun', 'had fun'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Service',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.02,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'number',
    ai_extraction_hints: ['service', 'served someone'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Hope',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.08,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 7,
    display_format: 'number',
    ai_extraction_hints: ['hope', 'hopeful'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Faith',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.15,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 8,
    display_format: 'number',
    ai_extraction_hints: ['faith', 'faithful'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Excited',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.01,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 9,
    display_format: 'number',
    ai_extraction_hints: ['excited', 'excitement'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Charity',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.12,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 10,
    display_format: 'number',
    ai_extraction_hints: ['charity', 'charitable'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Smell the Roses',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.30,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 11,
    display_format: 'number',
    ai_extraction_hints: ['present', 'mindful', 'smell the roses', 'grateful'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Negative (General)',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 12,
    display_format: 'number',
    ai_extraction_hints: ['negative', 'felt negative', 'bad mood'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Irritated',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 13,
    display_format: 'number',
    ai_extraction_hints: ['irritated', 'annoyed', 'frustrated'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Angry',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.12,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 14,
    display_format: 'number',
    ai_extraction_hints: ['angry', 'anger', 'mad'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Depressed',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.20,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 15,
    display_format: 'number',
    ai_extraction_hints: ['depressed', 'depression', 'down'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Sad',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 16,
    display_format: 'number',
    ai_extraction_hints: ['sad', 'sadness'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Fear',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 17,
    display_format: 'number',
    ai_extraction_hints: ['fear', 'afraid', 'scared'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Nervous',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.03,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 18,
    display_format: 'number',
    ai_extraction_hints: ['nervous', 'anxious', 'anxiety'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Hate',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.30,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 19,
    display_format: 'number',
    ai_extraction_hints: ['hate', 'hatred'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Homesick',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 20,
    display_format: 'number',
    ai_extraction_hints: ['homesick', 'miss home'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Woman Sick',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'negative',
    tier: 'monthly',
    display_order: 21,
    display_format: 'number',
    ai_extraction_hints: ['woman sick', 'lovesick'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Comforting from Heaven',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 22,
    display_format: 'number',
    ai_extraction_hints: ['comforted', 'comfort from heaven', 'spiritual comfort'],
    scale_min: 0,
    scale_max: 5,
  },

  // ── Emotional · Yearly ───────────────────────────────────────────────────
  {
    category_name: 'Emotional',
    name: 'Choosing to Find Comfort in God Each Month',
    measurement_type: 'scale',
    measurement_frequency: 'annual',
    weight: 0.55,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 23,
    display_format: 'number',
    ai_extraction_hints: ['comfort in god'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Feelings of Satisfaction for Labor for Family',
    measurement_type: 'scale',
    measurement_frequency: 'annual',
    weight: 0.10,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 24,
    display_format: 'number',
    ai_extraction_hints: ['satisfaction family'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Feelings of Satisfaction for Labor in Church',
    measurement_type: 'scale',
    measurement_frequency: 'annual',
    weight: 0.05,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 25,
    display_format: 'number',
    ai_extraction_hints: ['satisfaction church'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Emotional',
    name: 'Weekly Stress Reliever',
    measurement_type: 'binary',
    measurement_frequency: 'weekly',
    weight: 0.30,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 26,
    display_format: 'boolean',
    ai_extraction_hints: ['stress relief', 'stress release'],
    scale_min: 0,
    scale_max: 1,
  },

  // =========================================================================
  // 11.5 PHYSICAL
  // =========================================================================

  // ── Physical · Monthly ───────────────────────────────────────────────────
  {
    category_name: 'Physical',
    name: 'Daily Exercise',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.25,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'boolean',
    ai_extraction_hints: ['exercise', 'workout', 'worked out', 'gym', 'ran', 'lifted'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Physical',
    name: 'Eat Healthy',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.25,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'boolean',
    ai_extraction_hints: ['ate healthy', 'healthy food', 'clean eating'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Physical',
    name: 'A Good Night\'s Rest',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.25,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'boolean',
    ai_extraction_hints: ['slept well', 'good sleep', 'rested'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Physical',
    name: 'Daily Stretching / Mobility',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.25,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'boolean',
    ai_extraction_hints: ['stretched', 'stretching', 'mobility', 'yoga'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Physical',
    name: 'Strength Training',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'number',
    ai_extraction_hints: ['strength', 'lifting', 'weights'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Physical',
    name: 'Endurance Training',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'number',
    ai_extraction_hints: ['endurance', 'running', 'cardio run'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Physical',
    name: 'Cardiovascular',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 7,
    display_format: 'number',
    ai_extraction_hints: ['cardio', 'heart rate', 'cardiovascular'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Physical',
    name: 'Flexibility',
    measurement_type: 'scale',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 8,
    display_format: 'number',
    ai_extraction_hints: ['flexibility', 'flexible', 'stretch'],
    scale_min: 0,
    scale_max: 5,
  },
  {
    category_name: 'Physical',
    name: 'Vitamins / Minerals',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 9,
    display_format: 'boolean',
    ai_extraction_hints: ['vitamins', 'supplements', 'minerals'],
    scale_min: 0,
    scale_max: 1,
  },

  // ── Physical · Yearly ────────────────────────────────────────────────────
  {
    category_name: 'Physical',
    name: 'Ideal Weight Target (185 lbs)',
    measurement_type: 'target',
    measurement_frequency: 'annual',
    weight: 0.50,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 10,
    display_format: 'number',
    ai_extraction_hints: ['weight', 'current weight', 'weighed in'],
  },
  {
    category_name: 'Physical',
    name: 'Six Pack',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.50,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 11,
    display_format: 'boolean',
    ai_extraction_hints: ['six pack', 'abs', 'visible abs'],
    scale_min: 0,
    scale_max: 1,
  },

  // =========================================================================
  // 11.6 FINANCIAL
  // =========================================================================

  // ── Financial · Monthly ──────────────────────────────────────────────────
  {
    category_name: 'Financial',
    name: '$2000 Towards Storage Units Every Month',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.50,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'boolean',
    ai_extraction_hints: ['storage units', 'storage investment'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'Fast Offerings',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.05,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'boolean',
    ai_extraction_hints: ['fast offering'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: '0 Credit Card Interest',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'boolean',
    ai_extraction_hints: ['credit card', 'no interest', 'paid off cards'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'Spend Less Than You Make Every Month',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.40,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'boolean',
    ai_extraction_hints: ['under budget', 'spend less', 'saved money'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'Follow Budgeted Plan',
    measurement_type: 'binary',
    measurement_frequency: 'monthly',
    weight: 0.15,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'boolean',
    ai_extraction_hints: ['budget', 'followed budget'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'Write 10 Pages in Book Every Week',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.08,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 6,
    display_format: 'number',
    ai_extraction_hints: ['wrote pages', 'book writing', 'writing'],
    scale_min: 0,
    scale_max: 10,
  },

  // ── Financial · Yearly ───────────────────────────────────────────────────
  {
    category_name: 'Financial',
    name: 'Quarterly Search for Suitable Properties',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.40,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 7,
    display_format: 'boolean',
    ai_extraction_hints: ['property search', 'real estate'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'More Financially Secure Than Last Year',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.40,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 8,
    display_format: 'boolean',
    ai_extraction_hints: ['financially secure', 'net worth'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Financial',
    name: 'Wider Range of Investments Than Last Year',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.20,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 9,
    display_format: 'boolean',
    ai_extraction_hints: ['investments', 'diversified'],
    scale_min: 0,
    scale_max: 1,
  },

  // =========================================================================
  // 11.7 INTELLECTUAL
  // =========================================================================

  // ── Intellectual · Monthly ───────────────────────────────────────────────
  {
    category_name: 'Intellectual',
    name: 'Language Study',
    measurement_type: 'count',
    measurement_frequency: 'daily',
    weight: 1.0,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 1,
    display_format: 'hours',
    ai_extraction_hints: ['language study', 'studied language', 'thai', 'lao'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Intellectual',
    name: 'Podcast (~2 hours/week)',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 2,
    display_format: 'hours',
    ai_extraction_hints: ['podcast', 'listened to podcast'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Intellectual',
    name: 'Audiobook (~2 hours/week)',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 3,
    display_format: 'hours',
    ai_extraction_hints: ['audiobook', 'listened to book'],
    scale_min: 0,
    scale_max: 10,
  },
  {
    category_name: 'Intellectual',
    name: 'Greek/Latin Roots Flash Cards',
    measurement_type: 'binary',
    measurement_frequency: 'daily',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 4,
    display_format: 'boolean',
    ai_extraction_hints: ['flash cards', 'greek roots', 'latin roots'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Read About History',
    measurement_type: 'count',
    measurement_frequency: 'weekly',
    weight: 0.10,
    polarity: 'positive',
    tier: 'monthly',
    display_order: 5,
    display_format: 'hours',
    ai_extraction_hints: ['history', 'read history'],
    scale_min: 0,
    scale_max: 10,
  },

  // ── Intellectual · Yearly ────────────────────────────────────────────────
  {
    category_name: 'Intellectual',
    name: 'Novel',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 6,
    display_format: 'boolean',
    ai_extraction_hints: ['finished novel', 'read a novel'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Classical Book',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 7,
    display_format: 'boolean',
    ai_extraction_hints: ['classical book', 'classic literature'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Thai One Month Study',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 8,
    display_format: 'boolean',
    ai_extraction_hints: ['thai study', 'thai language'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Lao One Month Study',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 9,
    display_format: 'boolean',
    ai_extraction_hints: ['lao study', 'lao language'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Burmese One Month Study',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 10,
    display_format: 'boolean',
    ai_extraction_hints: ['burmese study', 'burmese language'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Memorize World Geography',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 11,
    display_format: 'boolean',
    ai_extraction_hints: ['world geography', 'countries'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Memorize Countries Gov/Population (Europe)',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 12,
    display_format: 'boolean',
    ai_extraction_hints: ['european countries', 'capitals'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'World History',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 13,
    display_format: 'boolean',
    ai_extraction_hints: ['world history'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Yearly BYU Independent Study Class',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.06,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 14,
    display_format: 'boolean',
    ai_extraction_hints: ['BYU', 'independent study', 'online class'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Soil Composition and Farming',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 15,
    display_format: 'boolean',
    ai_extraction_hints: ['soil', 'farming', 'agriculture'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Water Table',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 16,
    display_format: 'boolean',
    ai_extraction_hints: ['water table'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Why Can We Fly?',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 17,
    display_format: 'boolean',
    ai_extraction_hints: ['flight', 'aerodynamics'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Farthest Seen in Space',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 18,
    display_format: 'boolean',
    ai_extraction_hints: ['space', 'astronomy'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'How Does a Car Work?',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 19,
    display_format: 'boolean',
    ai_extraction_hints: ['car mechanics'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Nong Khai Fire Balls',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 20,
    display_format: 'boolean',
    ai_extraction_hints: ['nong khai', 'naga fireballs'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'What Makes Children More Patient?',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 21,
    display_format: 'boolean',
    ai_extraction_hints: ['children patience'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'How Pasteurized Milk Carries Less Bacteria',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 22,
    display_format: 'boolean',
    ai_extraction_hints: ['pasteurization', 'milk'],
    scale_min: 0,
    scale_max: 1,
  },
  {
    category_name: 'Intellectual',
    name: 'Conference in Every Language Each Session',
    measurement_type: 'binary',
    measurement_frequency: 'annual',
    weight: 0.04,
    polarity: 'positive',
    tier: 'yearly',
    display_order: 23,
    display_format: 'boolean',
    ai_extraction_hints: ['conference languages'],
    scale_min: 0,
    scale_max: 1,
  },

];

// ── Life Goals ──────────────────────────────────────────────────────────────

export const SEED_LIFE_GOALS: SeedLifeGoal[] = [
  // ── Spiritual Life Goals ─────────────────────────────────────────────────
  { category_name: 'Spiritual', name: 'Serve a Full Time Mission', weight: 0.15 },
  { category_name: 'Spiritual', name: 'Sealed in the Temple — Never Divorce', weight: 0.25 },
  { category_name: 'Spiritual', name: 'Be a Father', weight: 0.25 },
  { category_name: 'Spiritual', name: 'Live to See Patriarchal Blessings Fulfilled', weight: 0.35 },

  // ── Family Life Goals ────────────────────────────────────────────────────
  { category_name: 'Family', name: 'Get Married', weight: 1.0 },
  { category_name: 'Family', name: 'Become a Father', weight: 1.0 },

  // ── Personal Life Goals ──────────────────────────────────────────────────
  { category_name: 'Personal', name: 'Go Skydiving', weight: 0.125 },
  { category_name: 'Personal', name: 'Ride a Camel', weight: 0.125 },
  { category_name: 'Personal', name: 'Visit Gettysburg', weight: 0.125 },
  { category_name: 'Personal', name: 'Visit Niagara Falls', weight: 0.125 },
  { category_name: 'Personal', name: 'Visit Mount Rushmore', weight: 0.125 },
  { category_name: 'Personal', name: 'Visit Washington DC', weight: 0.125 },
  { category_name: 'Personal', name: 'See the Pyramids Live', weight: 0.125 },
  { category_name: 'Personal', name: 'See the Eiffel Tower', weight: 0.125 },

  // ── Emotional Life Goals ─────────────────────────────────────────────────
  { category_name: 'Emotional', name: 'Identify 45 Different Physical Stress Relief Activities', weight: 0.25 },
  { category_name: 'Emotional', name: 'Determine Negative Stressors vs. Positive Stressors', weight: 0.25 },
  { category_name: 'Emotional', name: 'Eliminate Negative Stressors', weight: 0.25 },
  { category_name: 'Emotional', name: 'Discover Proper Ways to Deal with Positive Stressors', weight: 0.25 },

  // ── Physical Life Goals ──────────────────────────────────────────────────
  { category_name: 'Physical', name: 'Marathon', weight: 0.09 },
  { category_name: 'Physical', name: 'Iron Man', weight: 0.09 },
  { category_name: 'Physical', name: 'Spartan', weight: 0.09 },
  { category_name: 'Physical', name: '1 Mile Swim', weight: 0.07 },
  { category_name: 'Physical', name: '50 Mile Bike Ride', weight: 0.09 },
  { category_name: 'Physical', name: '1000 Push Ups in a Row', weight: 0.09 },
  { category_name: 'Physical', name: '100 Pull Ups in a Row', weight: 0.09 },
  { category_name: 'Physical', name: '1000 Sit Ups in a Row', weight: 0.09 },
  { category_name: 'Physical', name: 'Always Keep the Six Pack', weight: 0.30 },

  // ── Financial Life Goals ─────────────────────────────────────────────────
  { category_name: 'Financial', name: 'Property Owner 10 Units', weight: 0.10 },
  { category_name: 'Financial', name: 'Property Owner 100 Units', weight: 0.14 },
  { category_name: 'Financial', name: 'Property Owner 500 Units', weight: 0.20 },
  { category_name: 'Financial', name: 'Publish First Book', weight: 0.15 },
  { category_name: 'Financial', name: 'Publish Second Book', weight: 0.15 },
  { category_name: 'Financial', name: 'Publish Third Book', weight: 0.15 },
  { category_name: 'Financial', name: 'Turn a Book Into a Movie', weight: 0.15 },
  { category_name: 'Financial', name: 'Retire from Having a Boss', weight: 0.10 },
  { category_name: 'Financial', name: 'Pay Off House', weight: 0.20 },
  { category_name: 'Financial', name: 'No Car Payments', weight: 0.20 },
  { category_name: 'Financial', name: 'Have No Debt and $5M (2010 Equivalent)', weight: 0.10 },

  // ── Intellectual Life Goals ──────────────────────────────────────────────
  { category_name: 'Intellectual', name: "Bachelor's Degree", weight: 0.20 },
  { category_name: 'Intellectual', name: "Master's Degree", weight: 0.20 },
  { category_name: 'Intellectual', name: 'PhD', weight: 0.20 },
  { category_name: 'Intellectual', name: 'Nuclear Physics', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Rocket Science', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Biology', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Chemistry', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Memorize Declaration of Independence', weight: 0.03 },
  { category_name: 'Intellectual', name: 'Memorize the United States Constitution', weight: 0.04 },
  { category_name: 'Intellectual', name: 'Memorize the Gettysburg Address', weight: 0.02 },
  { category_name: 'Intellectual', name: 'Learn to Play 21 Piano Songs', weight: 0.005 },
  { category_name: 'Intellectual', name: 'Learn to Play the Bag Pipes', weight: 0.05 },
  { category_name: 'Intellectual', name: 'Learn to Play the Accordion', weight: 0.04 },
  { category_name: 'Intellectual', name: 'Answer the Issue for Sticky Wages', weight: 1.0 },
  { category_name: 'Intellectual', name: 'Japanese Language', weight: 0.40 },
  { category_name: 'Intellectual', name: 'Arabic Language', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Swedish Language', weight: 0.20 },
  { category_name: 'Intellectual', name: 'German Language', weight: 0.20 },
  { category_name: 'Intellectual', name: 'Portuguese Language', weight: 0.05 },
  { category_name: 'Intellectual', name: 'Spanish Language', weight: 0.10 },
  { category_name: 'Intellectual', name: 'French Language', weight: 0.02 },
  { category_name: 'Intellectual', name: 'Latin or Greek Language', weight: 0.01 },
  { category_name: 'Intellectual', name: 'Biblical Hebrew', weight: 0.01 },

  // Ecclesiastical has no life goals.
];
